# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  x86ImageName: 'forex-import-x86'
  armImageName: 'forex-import-arm'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an x86 image
      inputs:
        command: build
        repository: $(x86ImageName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build an ARM image
      inputs:
        command: build
        repository: $(armImageName)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.arm'
        tags: |
          $(tag)