// Generated by https://quicktype.io

namespace forex_import.Models.Input
{
    using System;
    using System.Text.Json.Serialization;


    public partial class ForexSessionInDTO
    {
        [JsonPropertyName("sessionUser")]
        public SessionUser SessionUser { get; set; }

        [JsonPropertyName("startDate")]
        public string StartDate { get; set; }

        [JsonPropertyName("endDate")]
        public string EndDate { get; set; }

        [JsonPropertyName("currentTime")]
        public string CurrentTime { get; set; }

        [JsonPropertyName("lastUpdatedTime")]
        public string LastUpdatedTime { get; set; }

        [JsonPropertyName("sessionType")]
        public SessionType SessionType { get; set; }

        [JsonPropertyName("strategy")]
        public Strategy Strategy { get; set; }

        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("elapsedTime")]
        public string ElapsedTime { get; set; }

        [JsonPropertyName("beginSessionTime")]
        public string BeginSessionTime { get; set; }

        [JsonPropertyName("endSessionTime")]
        public string EndSessionTime { get; set; }

        [JsonPropertyName("experimentId")]
        public string ExperimentId { get; set; }

        [JsonPropertyName("percentComplete")]
        public double PercentComplete { get; set; }
    }

    public partial class SessionType
    {
        [JsonPropertyName("index")]
        public long Index { get; set; }
    }

    public partial class SessionUser
    {
        [JsonPropertyName("Accounts")]
        public Accounts Accounts { get; set; }
    }

    public partial class Accounts
    {
        [JsonPropertyName("primary")]
        public Account Primary { get; set; }

        [JsonPropertyName("secondary")]
        public Account Secondary { get; set; }
    }

    public partial class Account
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("cash")]
        public double Cash { get; set; }

        [JsonPropertyName("realizedPL")]
        public double RealizedPl { get; set; }

        [JsonPropertyName("Margin")]
        public double Margin { get; set; }

        [JsonPropertyName("MarginRatio")]
        public double MarginRatio { get; set; }

        [JsonPropertyName("idcount")]
        public long Idcount { get; set; }

        [JsonPropertyName("Trades")]
        public Trade[] Trades { get; set; }

        [JsonPropertyName("closedTrades")]
        public Trade[] ClosedTrades { get; set; }

        [JsonPropertyName("orders")]
        public Order[] Orders { get; set; }

        [JsonPropertyName("balanceHistory")]
        public BalanceHistory[] BalanceHistory { get; set; }
    }

    public partial class BalanceHistory
    {
        [JsonPropertyName("date")]
        public string Date { get; set; }

        [JsonPropertyName("amount")]
        public double Amount { get; set; }
    }

    public partial class Trade
    {
        [JsonPropertyName("pair")]
        public string Pair { get; set; }

        [JsonPropertyName("units")]
        public long Units { get; set; }

        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonPropertyName("openDate")]
        public string OpenDate { get; set; }

        [JsonPropertyName("closeDate")]
        public string? CloseDate { get; set; }

        [JsonPropertyName("openPrice")]
        public double OpenPrice { get; set; }

        [JsonPropertyName("closePrice")]
        public double ClosePrice { get; set; }

        [JsonPropertyName("stopLoss")]
        public double StopLoss { get; set; }

        [JsonPropertyName("takeProfit")]
        public double TakeProfit { get; set; }

        [JsonPropertyName("long")]
        public bool Long { get; set; }

        [JsonPropertyName("init")]
        public bool Init { get; set; }
    }

    public partial class Order
    {
        [JsonPropertyName("trade")]
        public Trade Trade { get; set; }

        [JsonPropertyName("triggerprice")]
        public double Triggerprice { get; set; }

        [JsonPropertyName("expired")]
        public bool Expired { get; set; }

        [JsonPropertyName("above")]
        public bool Above { get; set; }
    }

    public partial class Strategy
    {
        [JsonPropertyName("ruleName")]
        public string RuleName { get; set; }

        [JsonPropertyName("position")]
        public string Position { get; set; }

        [JsonPropertyName("window")]
        public long Window { get; set; }

        [JsonPropertyName("units")]
        public long Units { get; set; }

        [JsonPropertyName("stopLoss")]
        public double StopLoss { get; set; }

        [JsonPropertyName("takeProfit")]
        public double TakeProfit { get; set; }
    }


}
